config/routes.rb
Rails.application.routes.draw do
  resources :computers

  root :to => 'computers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computer.rb
class Computer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:name, :idf, :scep, :lab, :os, :college)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= form_for(computer) do |f| %>
  <% if computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% computer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :idf %>
    <%= f.check_box :idf %>
  </div>

  <div class="field">
    <%= f.label :scep %>
    <%= f.check_box :scep %>
  </div>

  <div class="field">
    <%= f.label :lab %>
    <%= f.check_box :lab %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label :college %>
    <%= f.text_field :college %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<h1>Editing Computer</h1>

<%= render 'form', computer: @computer %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Computers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Idf</th>
      <th>Scep</th>
      <th>Lab</th>
      <th>Os</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td><%= computer.name %></td>
        <td><%= computer.idf %></td>
        <td><%= computer.scep %></td>
        <td><%= computer.lab %></td>
        <td><%= computer.os %></td>
        <td><%= computer.college %></td>
        <td><%= link_to 'Show', computer %></td>
        <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
        <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computer', new_computer_path %>

app/views/computers/new.html.erb
<h1>New Computer</h1>

<%= render 'form', computer: @computer %>

<%= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @computer.name %>
</p>

<p>
  <strong>Idf:</strong>
  <%= @computer.idf %>
</p>

<p>
  <strong>Scep:</strong>
  <%= @computer.scep %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @computer.lab %>
</p>

<p>
  <strong>Os:</strong>
  <%= @computer.os %>
</p>

<p>
  <strong>College:</strong>
  <%= @computer.college %>
</p>

<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>